[package]
name = "shush"
version = "0.1.0"
edition = "2021"

[dependencies]
zeroize = "1.8.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2.158"
errno = "0.3.9"


[target.'cfg(windows)'.dependencies]
windows-sys = "0.59.0"
