name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # TODO: remove this when we cache the builds
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      run: rustup update

    - name: build
      run: cargo build --all --release

    - name: check
      run: cargo check --all --release

    - name: clippy
      run: cargo clippy --all-targets --release

    - name: doc
      run: cargo doc --workspace --all-features --no-deps
      
    - name: test
      run: cargo test --release --all-targets
      shell: bash
